version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/repo/hello-world

jobs:
  build:
    executor: node-executor
    steps:
      - checkout:
          path: ~/repo

      - run:
          name: Installer les dépendances npm
          command: npm install

      - run:
          name: Vérifier la version d'expo
          command: npx expo --version

      - run:
          name: Lancer les tests
          command: npm run test || echo "Pas de test configuré"

      - run:
          name: Générer le build Expo Web
          command: npx expo export --output-dir dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

